name: Publish
on:
  push:
    branches:
      - 'mkdocs'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: mkdocs build -s
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: site
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: site
        path: site
    - name: Publish
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_NAME: ${{ secrets.GH_NAME }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
      run: |
        REMOTE="https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
        git config --global user.name "${GH_NAME}"
        git config --global user.email "${GH_EMAIL}"
        git remote set-url origin ${REMOTE}
        ./publish.sh
